# Generated by Django 4.0 on 2023-07-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alienuser',
            name='username',
            field=models.CharField(default=1337, max_length=255, verbose_name='username'),
            preserve_default=False,
        ),
    ]
